-- Trackd - Supabase Database Schema
-- Copy and paste into SQL Editor in Supabase Dashboard

-- ============================================
-- TABLE: workout_templates
-- ============================================
CREATE TABLE IF NOT EXISTS public.workout_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    exercises jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT workout_templates_pkey PRIMARY KEY (id),
    CONSTRAINT workout_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable RLS on workout_templates
ALTER TABLE public.workout_templates ENABLE ROW LEVEL SECURITY;

-- RLS Policies for workout_templates
CREATE POLICY "Users can view own workouts" ON public.workout_templates
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create workouts" ON public.workout_templates
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own workouts" ON public.workout_templates
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own workouts" ON public.workout_templates
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- TABLE: completed_sessions
-- ============================================
CREATE TABLE IF NOT EXISTS public.completed_sessions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id uuid NOT NULL,
    workout_id bigint NOT NULL,
    completed_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    exercises jsonb DEFAULT '[]'::jsonb,
    duration integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT completed_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT completed_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT completed_sessions_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workout_templates(id) ON DELETE CASCADE
);

-- Enable RLS on completed_sessions
ALTER TABLE public.completed_sessions ENABLE ROW LEVEL SECURITY;

-- RLS Policies for completed_sessions
CREATE POLICY "Users can view own sessions" ON public.completed_sessions
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create sessions" ON public.completed_sessions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sessions" ON public.completed_sessions
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own sessions" ON public.completed_sessions
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- TABLE: personal_records
-- ============================================
CREATE TABLE IF NOT EXISTS public.personal_records (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id uuid NOT NULL,
    exercise text NOT NULL,
    weight numeric DEFAULT 0,
    reps numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT personal_records_pkey PRIMARY KEY (id),
    CONSTRAINT personal_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable RLS on personal_records
ALTER TABLE public.personal_records ENABLE ROW LEVEL SECURITY;

-- RLS Policies for personal_records
CREATE POLICY "Users can view own records" ON public.personal_records
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create records" ON public.personal_records
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own records" ON public.personal_records
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own records" ON public.personal_records
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- TABLE: user_settings
-- ============================================
CREATE TABLE IF NOT EXISTS public.user_settings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id uuid NOT NULL UNIQUE,
    settings jsonb DEFAULT '{"language": "en"}'::jsonb,
    theme text DEFAULT 'classic',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT user_settings_pkey PRIMARY KEY (id),
    CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable RLS on user_settings
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- RLS Policies for user_settings
CREATE POLICY "Users can view own settings" ON public.user_settings
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create settings" ON public.user_settings
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own settings" ON public.user_settings
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own settings" ON public.user_settings
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- INDEXES (for performance)
-- ============================================
CREATE INDEX idx_workout_templates_user_id ON public.workout_templates(user_id);
CREATE INDEX idx_completed_sessions_user_id ON public.completed_sessions(user_id);
CREATE INDEX idx_completed_sessions_workout_id ON public.completed_sessions(workout_id);
CREATE INDEX idx_personal_records_user_id ON public.personal_records(user_id);
CREATE INDEX idx_user_settings_user_id ON public.user_settings(user_id);
