const EXERCISE_LIST = [
  // Chest / Klatka Piersiowa
  { id: 'chest_1', name: 'Bench Press' },
  { id: 'chest_2', name: 'Bench Press - Paused' },
  { id: 'chest_3', name: 'Bench Press - Tempo' },
  { id: 'chest_4', name: 'Bench Press - Deficit' },
  { id: 'chest_5', name: 'Close Grip Bench Press' },
  { id: 'chest_6', name: 'Close Grip Bench Press - Paused' },
  { id: 'chest_7', name: 'Wide Grip Bench Press' },
  { id: 'chest_8', name: 'Wide Grip Bench Press - Paused' },
  { id: 'chest_9', name: 'Incline Bench Press' },
  { id: 'chest_10', name: 'Incline Bench Press - Paused' },
  { id: 'chest_11', name: 'Incline Bench Press - Close Grip' },
  { id: 'chest_12', name: 'Decline Bench Press' },
  { id: 'chest_13', name: 'Decline Bench Press - Paused' },
  { id: 'chest_14', name: 'Dumbbell Bench Press' },
  { id: 'chest_15', name: 'Dumbbell Bench Press - Paused' },
  { id: 'chest_16', name: 'Dumbbell Bench Press - Tempo' },
  { id: 'chest_17', name: 'Incline Dumbbell Bench Press' },
  { id: 'chest_18', name: 'Decline Dumbbell Bench Press' },
  { id: 'chest_19', name: 'Smith Machine Bench Press' },
  { id: 'chest_20', name: 'Smith Machine Incline Bench Press' },
  { id: 'chest_21', name: 'Chest Press Machine' },
  { id: 'chest_22', name: 'Chest Fly' },
  { id: 'chest_23', name: 'Dumbbell Fly' },
  { id: 'chest_24', name: 'Machine Fly' },
  { id: 'chest_25', name: 'Pec Deck' },
  { id: 'chest_26', name: 'Cable Flyes' },
  { id: 'chest_27', name: 'Incline Cable Fly' },
  { id: 'chest_28', name: 'Decline Cable Fly' },
  
  // Back / Plecy
  { id: 'back_1', name: 'Barbell Row' },
  { id: 'back_2', name: 'Barbell Row - Paused' },
  { id: 'back_3', name: 'Barbell Row - Tempo' },
  { id: 'back_4', name: 'Bent Over Barbell Row' },
  { id: 'back_5', name: 'Pendlay Row' },
  { id: 'back_6', name: 'Pendlay Row - Paused' },
  { id: 'back_7', name: 'T-Bar Row' },
  { id: 'back_8', name: 'T-Bar Row - Close Grip' },
  { id: 'back_9', name: 'Chest Supported Row' },
  { id: 'back_10', name: 'Chest Supported Row - Incline' },
  { id: 'back_11', name: 'Dumbbell Row' },
  { id: 'back_12', name: 'Dumbbell Row - Single Arm' },
  { id: 'back_13', name: 'Dumbbell Row - Paused' },
  { id: 'back_14', name: 'Single Arm Dumbbell Row' },
  { id: 'back_15', name: 'Single Arm Landmine Row' },
  { id: 'back_16', name: 'Machine Rows' },
  { id: 'back_17', name: 'Seated Row Machine' },
  { id: 'back_18', name: 'Seated Row Machine - Close Grip' },
  { id: 'back_19', name: 'Seated Row Machine - Wide Grip' },
  { id: 'back_20', name: 'Cable Rows' },
  { id: 'back_21', name: 'Cable Rows - Single Arm' },
  { id: 'back_22', name: 'Single Arm Cable Row' },
  { id: 'back_23', name: 'Resistance Band Rows' },
  { id: 'back_24', name: 'Smith Machine Row' },
  { id: 'back_25', name: 'Yates Row' },
  { id: 'back_26', name: 'Underhand Barbell Row' },
  { id: 'back_27', name: 'Seal Rows' },
  { id: 'back_28', name: 'Machine Chest Supported Row' },
  { id: 'back_29', name: 'Inverted Rows' },
  { id: 'back_30', name: 'Inverted Rows - Feet Elevated' },
  { id: 'back_31', name: 'Back Hyperextensions' },
  { id: 'back_32', name: 'Back Hyperextensions - Weighted' },
  { id: 'back_33', name: 'Back Hyperextensions - Decline' },
  { id: 'back_34', name: 'Good Mornings' },
  { id: 'back_35', name: 'Good Mornings - Wide Stance' },
  { id: 'back_36', name: 'Good Mornings - Close Stance' },
  { id: 'back_37', name: 'Shrugs' },
  { id: 'back_38', name: 'Barbell Shrugs' },
  { id: 'back_39', name: 'Barbell Shrugs - Wide Grip' },
  { id: 'back_40', name: 'Barbell Shrugs - Close Grip' },
  { id: 'back_41', name: 'Dumbbell Shrugs' },
  { id: 'back_42', name: 'Machine Shrugs' },
  { id: 'back_43', name: 'Smith Machine Shrugs' },
  { id: 'back_44', name: 'Lateral Shrugs' },
  { id: 'back_45', name: 'Upright Rows' },
  { id: 'back_46', name: 'Upright Rows - Close Grip' },
  { id: 'back_47', name: 'Upright Rows - Wide Grip' },
  { id: 'back_48', name: 'Cable Upright Rows' },

  // Shoulders / Ramiona
  { id: 'shoulders_1', name: 'Overhead Press' },
  { id: 'shoulders_2', name: 'Overhead Press - Paused' },
  { id: 'shoulders_3', name: 'Overhead Press - Tempo' },
  { id: 'shoulders_4', name: 'Standing Shoulder Press' },
  { id: 'shoulders_5', name: 'Standing Shoulder Press - Strict' },
  { id: 'shoulders_6', name: 'Seated Shoulder Press' },
  { id: 'shoulders_7', name: 'Seated Shoulder Press - Machine' },
  { id: 'shoulders_8', name: 'Smith Machine Shoulder Press' },
  { id: 'shoulders_9', name: 'Dumbbell Shoulder Press' },
  { id: 'shoulders_10', name: 'Dumbbell Shoulder Press - Paused' },
  { id: 'shoulders_11', name: 'Dumbbell Shoulder Press - Tempo' },
  { id: 'shoulders_12', name: 'Dumbbell Shoulder Press - Single Arm' },
  { id: 'shoulders_13', name: 'Landmine Press' },
  { id: 'shoulders_14', name: 'Landmine Press - Single Arm' },
  { id: 'shoulders_15', name: 'Floor Press' },
  { id: 'shoulders_16', name: 'Shoulder Raises' },
  { id: 'shoulders_17', name: 'Lateral Raises' },
  { id: 'shoulders_18', name: 'Lateral Raises - Machine' },
  { id: 'shoulders_19', name: 'Lateral Raises - Cable' },
  { id: 'shoulders_20', name: 'Front Raises' },
  { id: 'shoulders_21', name: 'Front Raises - Dumbbell' },
  { id: 'shoulders_22', name: 'Front Raises - Barbell' },
  { id: 'shoulders_23', name: 'Front Raises - Cable' },
  { id: 'shoulders_24', name: 'Front Raises - Plate' },
  { id: 'shoulders_25', name: 'Reverse Pec Deck' },
  { id: 'shoulders_26', name: 'Reverse Pec Deck - Machine' },
  { id: 'shoulders_27', name: 'Reverse Flyes' },
  { id: 'shoulders_28', name: 'Reverse Cable Flyes' },
  { id: 'shoulders_29', name: 'Face Pulls' },
  { id: 'shoulders_30', name: 'Face Pulls - Rope' },
  { id: 'shoulders_31', name: 'Face Pulls - Wide Attachment' },
  { id: 'shoulders_32', name: 'Lu Raises' },
  { id: 'shoulders_33', name: 'Pike Push-ups' },
  { id: 'shoulders_34', name: 'Pike Push-ups - Feet Elevated' },
  { id: 'shoulders_35', name: 'Cable Lateral Raises' },
  { id: 'shoulders_36', name: 'Machine Lateral Raises' },
  { id: 'shoulders_37', name: 'Plate Raises' },
  { id: 'shoulders_38', name: 'Plate Loaded Shoulder Press' },

  // Arms / Ręce
  { id: 'arms_1', name: 'Bicep Curls' },
  { id: 'arms_2', name: 'Bicep Curls - Barbell' },
  { id: 'arms_3', name: 'Bicep Curls - Dumbbell' },
  { id: 'arms_4', name: 'Bicep Curls - EZ Bar' },
  { id: 'arms_5', name: 'Bicep Curls - Machine' },
  { id: 'arms_6', name: 'Bicep Curls - Cable' },
  { id: 'arms_7', name: 'Bicep Curls - Paused' },
  { id: 'arms_8', name: 'Bicep Curls - Tempo' },
  { id: 'arms_9', name: 'Dumbbell Curls' },
  { id: 'arms_10', name: 'Dumbbell Curls - Incline' },
  { id: 'arms_11', name: 'Dumbbell Curls - Decline' },
  { id: 'arms_12', name: 'Dumbbell Curls - Single Arm' },
  { id: 'arms_13', name: 'Dumbbell Curls - Hammer Grip' },
  { id: 'arms_14', name: 'Barbell Curls' },
  { id: 'arms_15', name: 'Close Grip Barbell Curls' },
  { id: 'arms_16', name: 'Wide Grip Barbell Curls' },
  { id: 'arms_17', name: 'EZ Bar Curls' },
  { id: 'arms_18', name: 'EZ Bar Curls - Close Grip' },
  { id: 'arms_19', name: 'EZ Bar Curls - Wide Grip' },
  { id: 'arms_20', name: 'Machine Curls' },
  { id: 'arms_21', name: 'Cable Curls' },
  { id: 'arms_22', name: 'Cable Curls - Single Arm' },
  { id: 'arms_23', name: 'Preacher Curls' },
  { id: 'arms_24', name: 'Preacher Curls - Barbell' },
  { id: 'arms_25', name: 'Preacher Curls - Dumbbell' },
  { id: 'arms_26', name: 'Preacher Curls - Machine' },
  { id: 'arms_27', name: 'Incline Dumbbell Curls' },
  { id: 'arms_28', name: 'Concentration Curls' },
  { id: 'arms_29', name: 'Concentration Curls - Dumbbell' },
  { id: 'arms_30', name: 'Concentration Curls - Machine' },
  { id: 'arms_31', name: 'Hammer Curls' },
  { id: 'arms_32', name: 'Hammer Curls - Machine' },
  { id: 'arms_33', name: 'Reverse Curls' },
  { id: 'arms_34', name: 'Reverse Curls - Barbell' },
  { id: 'arms_35', name: 'Reverse Curls - Dumbbell' },
  { id: 'arms_36', name: 'Reverse Curls - Cable' },
  { id: 'arms_37', name: 'Zottman Curls' },
  { id: 'arms_38', name: 'Zottman Curls - Dumbbell' },
  { id: 'arms_39', name: 'Rope Curls' },
  { id: 'arms_40', name: 'Rope Curls - Cable' },
  { id: 'arms_41', name: 'Dragging Curls' },
  { id: 'arms_42', name: 'Scott Curls' },
  
  { id: 'triceps_1', name: 'Tricep Extensions' },
  { id: 'triceps_2', name: 'Tricep Extensions - Overhead' },
  { id: 'triceps_3', name: 'Tricep Extensions - Overhead Dumbbell' },
  { id: 'triceps_4', name: 'Tricep Extensions - Rope' },
  { id: 'triceps_5', name: 'Tricep Extensions - EZ Bar' },
  { id: 'triceps_6', name: 'Tricep Extensions - Barbell' },
  { id: 'triceps_7', name: 'Overhead Tricep Extension' },
  { id: 'triceps_8', name: 'Seated Overhead Tricep Extension' },
  { id: 'triceps_9', name: 'Standing Overhead Tricep Extension' },
  { id: 'triceps_10', name: 'Rope Tricep Pushdown' },
  { id: 'triceps_11', name: 'Rope Tricep Pushdown - Reverse Grip' },
  { id: 'triceps_12', name: 'Tricep Pushdown' },
  { id: 'triceps_13', name: 'Tricep Pushdown - V Bar' },
  { id: 'triceps_14', name: 'Tricep Pushdown - Straight Bar' },
  { id: 'triceps_15', name: 'Tricep Pushdown - Rope' },
  { id: 'triceps_16', name: 'Tricep Pushdown - Machine' },
  { id: 'triceps_17', name: 'Single Arm Tricep Pushdown' },
  { id: 'triceps_18', name: 'Tricep Kickbacks' },
  { id: 'triceps_19', name: 'Tricep Kickbacks - Dumbbell' },
  { id: 'triceps_20', name: 'Tricep Kickbacks - Machine' },
  { id: 'triceps_21', name: 'Skull Crushers' },
  { id: 'triceps_22', name: 'Skull Crushers - Barbell' },
  { id: 'triceps_23', name: 'Skull Crushers - Dumbbell' },
  { id: 'triceps_24', name: 'Skull Crushers - EZ Bar' },
  { id: 'triceps_25', name: 'Skull Crushers - Machine' },
  { id: 'triceps_26', name: 'Close Grip Floor Press' },
  { id: 'triceps_27', name: 'Machine Tricep Extension' },
  { id: 'triceps_28', name: 'Machine Tricep Dips' },
  { id: 'triceps_29', name: 'Dips Machine' },
  { id: 'triceps_30', name: 'Dips' },
  { id: 'triceps_31', name: 'Tricep Dips' },
  { id: 'triceps_32', name: 'Chest Dips' },
  { id: 'triceps_33', name: 'Dips - Machine Assisted' },
  { id: 'triceps_34', name: 'Dips - Weighted' },

  // Legs / Nogi
  { id: 'legs_1', name: 'Squat' },
  { id: 'legs_2', name: 'Squat - Paused' },
  { id: 'legs_3', name: 'Squat - Tempo' },
  { id: 'legs_4', name: 'Squat - High Bar' },
  { id: 'legs_5', name: 'Squat - Low Bar' },
  { id: 'legs_6', name: 'Squat - Safety Bar' },
  { id: 'legs_7', name: 'Front Squat' },
  { id: 'legs_8', name: 'Front Squat - Paused' },
  { id: 'legs_9', name: 'Front Squat - Tempo' },
  { id: 'legs_10', name: 'Goblet Squat' },
  { id: 'legs_11', name: 'Sissy Squat' },
  { id: 'legs_12', name: 'Sissy Squat - Bodyweight' },
  { id: 'legs_13', name: 'Sissy Squat - Machine' },
  { id: 'legs_14', name: 'Pistol Squats' },
  { id: 'legs_15', name: 'Pistol Squats - Assisted' },
  { id: 'legs_16', name: 'Pistol Squats - Box Assisted' },
  { id: 'legs_17', name: 'Belt Squat' },
  { id: 'legs_18', name: 'Belt Squat - Machine' },
  { id: 'legs_19', name: 'Pendulum Squat' },
  { id: 'legs_20', name: 'Smith Machine Squat' },
  { id: 'legs_21', name: 'Smith Machine Squat - High Bar' },
  { id: 'legs_22', name: 'Smith Machine Squat - Low Bar' },
  { id: 'legs_23', name: 'Hack Squat' },
  { id: 'legs_24', name: 'Hack Squat - Machine' },
  { id: 'legs_25', name: 'V Squat' },
  { id: 'legs_26', name: 'V Squat - Machine' },
  { id: 'legs_27', name: 'Leg Press' },
  { id: 'legs_28', name: 'Leg Press - V Stance' },
  { id: 'legs_29', name: 'Leg Press - Wide Stance' },
  { id: 'legs_30', name: 'Leg Press - Close Stance' },
  { id: 'legs_31', name: 'Plate Loaded Leg Press' },
  { id: 'legs_32', name: 'Single Leg Press' },
  { id: 'legs_33', name: 'Single Leg Leg Press' },
  { id: 'legs_34', name: 'Decline Leg Press' },
  { id: 'legs_35', name: 'Incline Leg Press' },
  
  { id: 'lunges_1', name: 'Lunges' },
  { id: 'lunges_2', name: 'Walking Lunges' },
  { id: 'lunges_3', name: 'Walking Lunges - Dumbbell' },
  { id: 'lunges_4', name: 'Walking Lunges - Barbell' },
  { id: 'lunges_5', name: 'Stationary Lunges' },
  { id: 'lunges_6', name: 'Reverse Lunges' },
  { id: 'lunges_7', name: 'Reverse Lunges - Dumbbell' },
  { id: 'lunges_8', name: 'Reverse Lunges - Machine' },
  { id: 'lunges_9', name: 'Bulgarian Split Squats' },
  { id: 'lunges_10', name: 'Bulgarian Split Squats - Dumbbell' },
  { id: 'lunges_11', name: 'Bulgarian Split Squats - Barbell' },
  { id: 'lunges_12', name: 'Bulgarian Split Squats - Machine' },
  { id: 'lunges_13', name: 'Single Leg RDL' },
  { id: 'lunges_14', name: 'Single Leg RDL - Dumbbell' },
  { id: 'lunges_15', name: 'Single Leg RDL - Barbell' },
  { id: 'lunges_16', name: 'Single Leg RDL - Machine' },
  { id: 'lunges_17', name: 'Curtsy Lunges' },
  { id: 'lunges_18', name: 'Lateral Lunges' },
  { id: 'lunges_19', name: 'Machine Lunges' },
  
  { id: 'deadlifts_1', name: 'Deadlift' },
  { id: 'deadlifts_2', name: 'Deadlift - Paused' },
  { id: 'deadlifts_3', name: 'Deadlift - Tempo' },
  { id: 'deadlifts_4', name: 'Deadlift - Deficit' },
  { id: 'deadlifts_5', name: 'Deadlift - Conventional' },
  { id: 'deadlifts_6', name: 'Deadlift - Sumo' },
  { id: 'deadlifts_7', name: 'Deadlift - Trap Bar' },
  { id: 'deadlifts_8', name: 'Deadlift - Safety Bar' },
  { id: 'deadlifts_9', name: 'Romanian Deadlift' },
  { id: 'deadlifts_10', name: 'Romanian Deadlift - Paused' },
  { id: 'deadlifts_11', name: 'Romanian Deadlift - Dumbbell' },
  { id: 'deadlifts_12', name: 'Romanian Deadlift - Machine' },
  { id: 'deadlifts_13', name: 'Sumo Deadlift' },
  { id: 'deadlifts_14', name: 'Sumo Deadlift - Paused' },
  { id: 'deadlifts_15', name: 'Trap Bar Deadlift' },
  { id: 'deadlifts_16', name: 'Trap Bar Deadlift - High Handle' },
  { id: 'deadlifts_17', name: 'Trap Bar Deadlift - Low Handle' },
  { id: 'deadlifts_18', name: 'Safety Bar Deadlift' },
  { id: 'deadlifts_19', name: 'Block Pull' },
  { id: 'deadlifts_20', name: 'Block Pull - Deficit' },
  { id: 'deadlifts_21', name: 'Pin Squats' },
  { id: 'deadlifts_22', name: 'Partial Deadlifts' },
  { id: 'deadlifts_23', name: 'Rack Pulls' },
  { id: 'deadlifts_24', name: 'Rack Pulls - Knee Height' },
  { id: 'deadlifts_25', name: 'Rack Pulls - Hip Height' },

  { id: 'hamstring_1', name: 'Leg Curls' },
  { id: 'hamstring_2', name: 'Leg Curls - Machine' },
  { id: 'hamstring_3', name: 'Leg Curls - Lying' },
  { id: 'hamstring_4', name: 'Leg Curls - Seated' },
  { id: 'hamstring_5', name: 'Leg Curls - Standing' },
  { id: 'hamstring_6', name: 'Leg Curls - Single Leg' },
  { id: 'hamstring_7', name: 'Lying Leg Curls' },
  { id: 'hamstring_8', name: 'Seated Leg Curls' },
  { id: 'hamstring_9', name: 'Standing Leg Curls' },
  { id: 'hamstring_10', name: 'Nordic Curls' },
  { id: 'hamstring_11', name: 'Nordic Curls - Assisted' },
  { id: 'hamstring_12', name: 'Nordic Curls - Machine Assisted' },
  { id: 'hamstring_13', name: 'Machine Leg Curls' },
  { id: 'hamstring_14', name: 'Single Leg Machine Curls' },

  { id: 'quads_1', name: 'Leg Extensions' },
  { id: 'quads_2', name: 'Leg Extensions - Machine' },
  { id: 'quads_3', name: 'Leg Extensions - Single Leg' },
  { id: 'quads_4', name: 'Machine Leg Extensions' },
  { id: 'quads_5', name: 'Single Leg Machine Extensions' },

  { id: 'calves_1', name: 'Calf Raises' },
  { id: 'calves_2', name: 'Calf Raises - Standing' },
  { id: 'calves_3', name: 'Calf Raises - Barbell' },
  { id: 'calves_4', name: 'Calf Raises - Dumbbell' },
  { id: 'calves_5', name: 'Calf Raises - Machine' },
  { id: 'calves_6', name: 'Calf Raises - Seated' },
  { id: 'calves_7', name: 'Calf Raises - Smith Machine' },
  { id: 'calves_8', name: 'Calf Raises - Single Leg' },
  { id: 'calves_9', name: 'Seated Calf Raises' },
  { id: 'calves_10', name: 'Barbell Calf Raises' },
  { id: 'calves_11', name: 'Dumbbell Calf Raises' },
  { id: 'calves_12', name: 'Smith Machine Calf Raises' },
  { id: 'calves_13', name: 'Plate Loaded Calf Raises' },
  { id: 'calves_14', name: 'Donkey Calf Raises' },

  // Pull movements / Ciągi
  { id: 'pull_1', name: 'Pull-ups' },
  { id: 'pull_2', name: 'Pull-ups - Wide Grip' },
  { id: 'pull_3', name: 'Pull-ups - Close Grip' },
  { id: 'pull_4', name: 'Pull-ups - Neutral Grip' },
  { id: 'pull_5', name: 'Pull-ups - Weighted' },
  { id: 'pull_6', name: 'Pull-ups - Assisted' },
  { id: 'pull_7', name: 'Pull-ups - Slow Tempo' },
  { id: 'pull_8', name: 'Chin-ups' },
  { id: 'pull_9', name: 'Chin-ups - Weighted' },
  { id: 'pull_10', name: 'Chin-ups - Assisted' },
  { id: 'pull_11', name: 'Neutral Grip Pull-ups' },
  { id: 'pull_12', name: 'Wide Grip Lat Pulldown' },
  { id: 'pull_13', name: 'Lat Pulldowns' },
  { id: 'pull_14', name: 'Lat Pulldowns - Close Grip' },
  { id: 'pull_15', name: 'Lat Pulldowns - Wide Grip' },
  { id: 'pull_16', name: 'Lat Pulldowns - Machine' },
  { id: 'pull_17', name: 'Lat Pulldowns - Single Arm' },
  { id: 'pull_18', name: 'Reverse Grip Lat Pulldown' },
  { id: 'pull_19', name: 'V Bar Pulldowns' },
  { id: 'pull_20', name: 'Machine Lat Pulldowns' },
  { id: 'pull_21', name: 'Single Arm Lat Pulldown' },

  // Core / Brzuch
  { id: 'core_1', name: 'Planks' },
  { id: 'core_2', name: 'Planks - Weighted' },
  { id: 'core_3', name: 'Planks - Decline' },
  { id: 'core_4', name: 'Side Planks' },
  { id: 'core_5', name: 'Side Planks - Weighted' },
  { id: 'core_6', name: 'Side Planks - Machine' },
  { id: 'core_7', name: 'Ab Wheel Rollout' },
  { id: 'core_8', name: 'Ab Wheel Rollout - Kneeling' },
  { id: 'core_9', name: 'Ab Wheel Rollout - Standing' },
  { id: 'core_10', name: 'Ab Wheel Rollout - Machine' },
  { id: 'core_11', name: 'Cable Crunches' },
  { id: 'core_12', name: 'Cable Crunches - Machine' },
  { id: 'core_13', name: 'Machine Crunches' },
  { id: 'core_14', name: 'Machine Crunches - Weighted' },
  { id: 'core_15', name: 'Crunches' },
  { id: 'core_16', name: 'Crunches - Machine' },
  { id: 'core_17', name: 'Crunches - Weighted' },
  { id: 'core_18', name: 'Decline Crunches' },
  { id: 'core_19', name: 'Leg Raises' },
  { id: 'core_20', name: 'Leg Raises - Machine' },
  { id: 'core_21', name: 'Leg Raises - Dumbbell' },
  { id: 'core_22', name: 'Leg Raises - Weighted' },
  { id: 'core_23', name: 'Hanging Leg Raises' },
  { id: 'core_24', name: 'Hanging Knee Raises' },
  { id: 'core_25', name: 'Hanging Knee Raises - Machine' },
  { id: 'core_26', name: 'Cable Crunch' },
  { id: 'core_27', name: 'Cable Crunch - Rope' },
  { id: 'core_28', name: 'Pallof Press' },
  { id: 'core_29', name: 'Pallof Press - Cable' },
  { id: 'core_30', name: 'Pallof Press - Single Arm' },
  { id: 'core_31', name: 'Ab Crunch Machine' },
  { id: 'core_32', name: 'Captain\'s Chair Leg Raises' },

  // Bodyweight / Calisthenics
  { id: 'bodyweight_1', name: 'Push-ups' },
  { id: 'bodyweight_2', name: 'Push-ups - Standard' },
  { id: 'bodyweight_3', name: 'Push-ups - Wide Grip' },
  { id: 'bodyweight_4', name: 'Push-ups - Diamond' },
  { id: 'bodyweight_5', name: 'Push-ups - Decline' },
  { id: 'bodyweight_6', name: 'Push-ups - Incline' },
  { id: 'bodyweight_7', name: 'Push-ups - Close Grip' },
  { id: 'bodyweight_8', name: 'Push-ups - Archer' },
  { id: 'bodyweight_9', name: 'Push-ups - Pseudo Planche' },
  { id: 'bodyweight_10', name: 'Push-ups - Weighted' },
  { id: 'bodyweight_11', name: 'Hindu Pushups' },
  { id: 'bodyweight_12', name: 'Hindu Pushups - Slow Tempo' },
  { id: 'bodyweight_13', name: 'Explosive Push-ups' },
  { id: 'bodyweight_14', name: 'One Arm Push-ups' },
  { id: 'bodyweight_15', name: 'One Arm Push-ups - Assisted' },
  { id: 'bodyweight_16', name: 'Burpees' },
  { id: 'bodyweight_17', name: 'Burpees - Weighted' },
  { id: 'bodyweight_18', name: 'Burpees - Box' },
  { id: 'bodyweight_19', name: 'Dragon Flags' },
  { id: 'bodyweight_20', name: 'Dragon Flags - Assisted' },
  { id: 'bodyweight_21', name: 'Dragon Flags - Machine' },
  { id: 'bodyweight_22', name: 'Handstand Push-ups' },
  { id: 'bodyweight_23', name: 'Handstand Push-ups - Wall Assisted' },
  { id: 'bodyweight_24', name: 'Muscle-ups' },
  { id: 'bodyweight_25', name: 'Muscle-ups - Assisted' },
  { id: 'bodyweight_26', name: 'L-sit Holds' },
  { id: 'bodyweight_27', name: 'L-sit Holds - Machine' },
  { id: 'bodyweight_28', name: 'Jumping Jacks' },
  { id: 'bodyweight_29', name: 'Mountain Climbers' },
  { id: 'bodyweight_30', name: 'Bear Crawls' },

  // General / Inne
  { id: 'general_1', name: 'Rows' },
  { id: 'general_2', name: 'Back Extensions' },
  { id: 'general_3', name: 'Plate Loaded Machine' },
  { id: 'general_4', name: 'Multi-Grip Machine' },
  { id: 'general_5', name: 'Custom Exercise' }
].sort((a, b) => a.name.localeCompare(b.name));

export default EXERCISE_LIST;
