const EXERCISE_LIST = [
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Dumbbell Bench Press',
  'Squat',
  'Front Squat',
  'Hack Squat',
  'Leg Press',
  'Deadlift',
  'Romanian Deadlift',
  'Sumo Deadlift',
  'Overhead Press',
  'Standing Shoulder Press',
  'Seated Shoulder Press',
  'Barbell Row',
  'Dumbbell Row',
  'Pendlay Row',
  'T-Bar Row',
  'Chest Fly',
  'Dumbbell Fly',
  'Pull-ups',
  'Chin-ups',
  'Lat Pulldowns',
  'Wide Grip Lat Pulldown',
  'Dips',
  'Tricep Dips',
  'Chest Dips',
  'Lunges',
  'Walking Lunges',
  'Bulgarian Split Squats',
  'Leg Curls',
  'Leg Extensions',
  'Bicep Curls',
  'Dumbbell Curls',
  'Barbell Curls',
  'Machine Curls',
  'Tricep Extensions',
  'Overhead Tricep Extension',
  'Rope Tricep Pushdown',
  'Tricep Kickbacks',
  'Shoulder Raises',
  'Lateral Raises',
  'Front Raises',
  'Reverse Pec Deck',
  'Machine Rows',
  'Planks',
  'Side Planks',
  'Ab Wheel Rollout',
  'Cable Crunches',
  'Machine Crunches',
  'Leg Raises',
  'Hanging Leg Raises',
  'Burpees',
  'Push-ups',
  'Wide Grip Push-ups',
  'Diamond Push-ups',
  'Decline Push-ups',
  'Facepulls',
  'Shrugs',
  'Dumbbell Shrugs',
  'Barbell Shrugs',
  'Machine Shrugs',
  'Upright Rows',
  'Cable Lateral Raises',
  'Smith Machine Squat',
  'Smith Machine Bench Press',
  'Smith Machine Row',
  'Seated Row Machine',
  'Chest Press Machine',
  'Shoulder Press Machine',
  'Cable Flyes',
  'Machine Fly',
  'Pec Deck',
  'Calf Raises',
  'Seated Calf Raises',
  'Barbell Calf Raises',
  'Dumbbell Calf Raises',
  'Smith Machine Calf Raises',
  'Preacher Curls',
  'EZ Bar Curls',
  'Cable Curls',
  'Hammer Curls',
  'Incline Dumbbell Curls',
  'Close Grip Bench Press',
  'Skull Crushers',
  'Dips Machine',
  'V Bar Pulldowns',
  'Reverse Grip Lat Pulldown',
  'Single Arm Rows',
  'Single Arm Lat Pulldown',
  'Cable Rows',
  'Resistance Band Rows',
  'Chest Supported Row',
  'Back Hyperextensions',
  'Good Mornings',
  'Pendulum Squat',
  'Plate Loaded Leg Press',
  'V Squat'
];

export default EXERCISE_LIST;
